### ISSUE TITLE
Move to maxmind v2 libs?

### ISSUE THREAD

**Issue by dgryski** [dgryski/rgip#6]
The v1 api is being deprecated.  Worth upgrading to v2. Note this requires a new Go library. Currently there is a pure Go implementation but not bindings for the official C library.

**Comment by dgryski** [comment]
https://github.com/oschwald/geoip2-golang

**Comment by dgryski** [comment]
This will also involve figuring out which fields from the various struct we want to export.  English name probably yes, all the translations, probably no.

**Comment by dgryski** [comment]
The gc pauses from using this library rather than the cgo v1 library are very noticeable,  causing request times to spike to 300ms (add measured with vegeta ). Using 1.5 eliminates these stalls.

**Comment by oschwald** [comment]
I'm not sure what your performance requirements are, but you will likely see an improvement if you use [maxminddb](https://github.com/oschwald/maxminddb-golang) directly with a [struct](https://github.com/oschwald/geoip2-golang/blob/master/reader.go#L15) that only has the data you want. The reader does not read out values that it does not need to populate the struct.

**Comment by dgryski** [comment]
Initial implementation in 8a33e7326b781bfc85895961cc365dd62f5da89c

**Comment by dgryski** [comment]
Closing.  Future v2 issues can be filed as separate bugs.
