### ISSUE TITLE
Speed loading with binary files and mmap

### ISSUE THREAD

**Issue by dgryski** [dgryski/rgip#7]
Currently rgip takes 10s or so to start up. This time is entirely loading the two csv data files into memory for a total of about 6M lines to parse. We can speed this to mostly instant by creating a binary file we can mmap into our process space and search directly. This should be easy since they're both just arrays of structs of integers.

**Comment by JaderDias** [comment]
It seems only one of the necessary dat files is free. Is there any way I could obtain the other 2?
